### ISSUE TITLE
JAVADOC

### ISSUE THREAD

**Issue by RobertoDimatteo** [RobertoDimatteo/MAP#3]
Applicazione di commenti JavaDoc al codice

Link utili:

https://www.oracle.com/it/technical-resources/articles/java/javadoc-tool.html#tag (pagina generale di javadoc)

https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#javadoctags (descrizione dei tag con esempi)

https://www.oracle.com/java/technologies/javase/javadoc-faq.html (pagina FAQ)

**Comment by Lunalorla** [comment]
**Return** Tag:

Adds a "Returns" section with the description text. This text should describe the return type and permissible range of values.
You can only have a single "return" tag in a Javadoc comment.
**Omit**  "return" for methods that return **void** and for **constructors**; include it for all other methods.

**Comment by Lunalorla** [comment]
Order of Tags:

- param
- return
- throws

**Comment by Lunalorla** [comment]
Ordering Multiple Tags:

Multiple **"param"** tags should be listed in argument-declaration order. This makes it easier to visually match the list to the declaration.

Multiple **"throws"** tags should be listed alphabetically by the exception names.

**Comment by Lunalorla** [comment]
**Param** Tag:

The **"param"** tag is followed by the **name** (not data type) of the parameter, followed by a description of the parameter. By convention, the first noun in the description is the data type of the parameter. (Articles like "a", "an", and "the" can precede the noun.) 
An exception is made for the primitive **int**, where the data type is usually omitted. 
Additional spaces can be inserted between the name and description so that the descriptions line up in a block.

**Comment by Lunalorla** [comment]
**Throws** Tag:

A **"throws"** tag should be included for any **checked** exceptions (declared in the throws clause) and also for any **unchecked** exceptions that the caller might reasonably want to catch. 
Errors should not be documented as they are unpredictable.

**Comment by Lunalorla** [comment]
when using "<" ad ">" in javadoc, it does not appear the element on the inside, because tags have special functions on formatting texts.
It can be used  **&lt;** for **<** and **&gt;** for **>** .
